### ISSUE TITLE
Assalamualaikum 

### ISSUE THREAD

**Issue by reshadmrrr** [maifeeulasad/CSECU-repo-curation#2]
### Prerequisites

* [ ] Are/were you student of CSE.CU? Yes, I am.
* [ ] Was this project graded? Not yet. 
* [ ] Does this project have some licensing issues? It has GNU General Public License.  

### Details

0. RSA Calculator
1. Monayam Reshad
2. 16701080
3. https://github.com/reshadmrrr/rsa_calculator
4. [Some reference, to boost up verification speed]
5. completed
6. Oct 4, 2020
7. CSE 717
8. 
9. details can be found in the project description
10. approximately a week
11. 
12. 
13. Would love to do so.

**Comment by maifeeulasad** [comment]
Thanks @reshadmrrr for your contribution, I will let you know when I've updated the readme.

**Comment by maifeeulasad** [comment]
@reshadmrrr I'm closing this for now as I have added it.

Don't forget to check it out : https://github.com/maifeeulasad/CSECU-repo-curation/tree/09f50fb07478a95fb81ff332cf08767387545be7

More details : https://github.com/maifeeulasad/CSECU-repo-curation/commit/09f50fb07478a95fb81ff332cf08767387545be7

If there is any problem, please let me know. And contribute as much as possible.
Thanks.
