### ISSUE TITLE
Corona Stats

### ISSUE THREAD

**Issue by naimur978** [maifeeulasad/CSECU-repo-curation#3]
### Prerequisites

* [ ] Are/were you student of CSE.CU ? Yeap, I'm.
* [ ] Was this project graded ? Nope.
* [ ] Does this project have some licensing issues ? GPL-2.0 License.

### Details

0. Corona Stats 
1. Naimur Rahman
2. 17701045
3. https://github.com/naimur978/Corona-Statistics
4. https://drive.google.com/file/d/12ZgQdkufa-FwG3vYasqA7GDaZ623aKWd/view
5. Accomplished
6. May 17, 2020
7. 
8. 
9. One can see the real-time info about Corona around the world.
10. Around 1 week.
11. 
12. 
13. I'd really love to do so.

**Comment by maifeeulasad** [comment]
added at https://github.com/maifeeulasad/CSECU-repo-curation/commit/25f476906e7d3e034b8460a9bd650537cda1dd51

@naimur978 please check, if there is anything more please let me know
