### ISSUE TITLE
Requesting to add the given info

### ISSUE THREAD

**Issue by naimur978** [maifeeulasad/CSECU-repo-curation#4]
### Prerequisites

* [ ] Are/were you student of CSE.CU ? Yea.
* [ ] Was this project graded ? No.
* [ ] Does this project have some licensing issues ? MIT License

### Details

0. Track Your Buddy
1. Naimur Rahman
2. 17701045
3. https://github.com/naimur978/Track-Your-Buddy
4. https://drive.google.com/file/d/1zj8JLYEeiD2RcmL1NFB7RObZBDfez9-L/view?usp=sharing
5. Accomplished
6. 21 February 2020
7. 
8. 
9. Having this app, you can detect your friends in real-time.
10. 2 weeks.
11. 
12.
13. Yea, I would like to.

**Comment by maifeeulasad** [comment]
added at https://github.com/maifeeulasad/CSECU-repo-curation/commit/fb60c7fcce7fe5fe72b09c1a04a44cd4feb6e35f

@naimur978 it will be really heartily if you check once more, here - https://github.com/maifeeulasad/CSECU-repo-curation/tree/fb60c7fcce7fe5fe72b09c1a04a44cd4feb6e35f
