### ISSUE TITLE
Requesting to add the given info

### ISSUE THREAD

**Issue by ahs95** [maifeeulasad/CSECU-repo-curation#5]
### Prerequisites

* [ ] Are/were you student of CSE.CU ? Yes 
* [ ] Was this project graded ? No 
* [ ] Does this project have some licensing issues ? No 

### Details

0. Simple Blog Site 
1. Arshadul Hoque 
2. 16701069
3. https://github.com/ahs95/Simple-blog-site-
4. 
5. Completed
6. Jan 2020
7. 
8. 
9. By using this blog, user can create, update, delete posts about tech, education, travelling and so on.  
10. 2 months 
11. 
12. 
13.

**Comment by maifeeulasad** [comment]
added on https://github.com/maifeeulasad/CSECU-repo-curation/commit/af97503d73a82f0873f697aab4dc5b79733ddd8b

vai, please check and tell me if there is something more to added or edited, it's available here : https://github.com/maifeeulasad/CSECU-repo-curation/blob/af97503d73a82f0873f697aab4dc5b79733ddd8b/README.md
